# Generated by Django 5.0.6 on 2024-07-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.AddField(
            model_name='expense',
            name='categorys',
            field=models.CharField(default=1, max_length=550),
        ),
    ]
